ADDRESS: http://0.0.0.0
APP:
  PORT: 5554

TRANSPORTATION:
  PORT: 5556
  WEIGHT: weights/transportation.pth

PEDESTRON:
  PORT: 5567
  CONFIG: models/Pedestron/configs/elephant/cityperson/cascade_hrnet.py
  WEIGHT: weights/CascadeRCNNCP_model.pth.stu

CAMERA_MONITOR:
  SLEEP_TIME: 1
  USE_HEATMAP: True 

NOTIFICATION:  
  USERNAME: nero18@apcs.vn
  PASSWORD: Nguyenero123! 

  BASE_URL: http://portal-notification-cxnam-ews.education.wise-paas.com/api/

  THRESHOLD: 20
  # Delta time between two notifications 
  INTERVAL: 300